"""knowledge entries + service long-form fields

Revision ID: 8a72e4883e02
Revises: c77e47914ea3
Create Date: 2026-04-30 13:12:48.633414

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '8a72e4883e02'
down_revision: str | None = 'c77e47914ea3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_entries',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('related_service_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_entries_business_id'), 'knowledge_entries', ['business_id'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_category'), 'knowledge_entries', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_is_demo'), 'knowledge_entries', ['is_demo'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_language'), 'knowledge_entries', ['language'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_related_service_id'), 'knowledge_entries', ['related_service_id'], unique=False)
    # server_default lets us add NOT NULL columns to a table that already
    # has rows — Postgres backfills with `{}` for existing services.
    op.add_column('services', sa.Column('details_long', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.add_column('services', sa.Column('pre_care', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.add_column('services', sa.Column('post_care', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.add_column('services', sa.Column('contraindications', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.add_column('services', sa.Column('insurance_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'insurance_notes')
    op.drop_column('services', 'contraindications')
    op.drop_column('services', 'post_care')
    op.drop_column('services', 'pre_care')
    op.drop_column('services', 'details_long')
    op.drop_index(op.f('ix_knowledge_entries_related_service_id'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_language'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_is_demo'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_category'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_business_id'), table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    # ### end Alembic commands ###
