"""initial

Revision ID: b005659e4bbf
Revises: 
Create Date: 2026-04-28 08:31:39.040162

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b005659e4bbf'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.Enum('restaurant', 'clinic', 'dental', 'beauty', 'real_estate', 'other', name='business_domain'), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('default_language', sa.String(length=8), nullable=False),
    sa.Column('supported_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_businesses_is_demo'), 'businesses', ['is_demo'], unique=False)
    op.create_table('channels',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('whatsapp', 'web', 'instagram', name='channel_type'), nullable=False),
    sa.Column('external_account_id', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'disconnected', name='channel_status'), nullable=False),
    sa.Column('credentials_reference', sa.String(length=256), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'external_account_id', name='uq_channel_type_account')
    )
    op.create_index(op.f('ix_channels_business_id'), 'channels', ['business_id'], unique=False)
    op.create_table('customers',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.Enum('whatsapp', 'web', 'instagram', name='channel_type'), nullable=False),
    sa.Column('external_user_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('instagram_username', sa.String(length=64), nullable=True),
    sa.Column('preferred_language', sa.String(length=8), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'channel_type', 'external_user_id', name='uq_customer_business_channel_user')
    )
    op.create_index(op.f('ix_customers_business_id'), 'customers', ['business_id'], unique=False)
    op.create_index(op.f('ix_customers_is_demo'), 'customers', ['is_demo'], unique=False)
    op.create_table('tool_idempotency',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('business_id', 'tool_name', 'idempotency_key')
    )
    op.create_table('conversations',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.Enum('whatsapp', 'web', 'instagram', name='channel_type'), nullable=False),
    sa.Column('status', sa.Enum('active', 'waiting_customer', 'human_needed', 'closed', name='conversation_status'), nullable=False),
    sa.Column('current_intent', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_business_id'), 'conversations', ['business_id'], unique=False)
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_conversations_is_demo'), 'conversations', ['is_demo'], unique=False)
    op.create_table('ai_runs',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('classifier_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('router_decision', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('redacted_prompt', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_runs_conversation_id'), 'ai_runs', ['conversation_id'], unique=False)
    op.create_table('bookings',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('service_type', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'rescheduled', 'no_show', name='booking_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('external_calendar_event_id', sa.String(length=256), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_business_id'), 'bookings', ['business_id'], unique=False)
    op.create_index(op.f('ix_bookings_conversation_id'), 'bookings', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_date'), 'bookings', ['date'], unique=False)
    op.create_index(op.f('ix_bookings_is_demo'), 'bookings', ['is_demo'], unique=False)
    op.create_index(op.f('ix_bookings_resource_id'), 'bookings', ['resource_id'], unique=False)
    op.create_table('handoff_tasks',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'claimed', 'resolved', 'cancelled', name='handoff_status'), nullable=False),
    sa.Column('assigned_to', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handoff_tasks_business_id'), 'handoff_tasks', ['business_id'], unique=False)
    op.create_index(op.f('ix_handoff_tasks_conversation_id'), 'handoff_tasks', ['conversation_id'], unique=False)
    op.create_table('leads',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('new', 'qualified', 'contacted', 'won', 'lost', name='lead_status'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('value_estimate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('next_action', sa.String(length=256), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_business_id'), 'leads', ['business_id'], unique=False)
    op.create_index(op.f('ix_leads_conversation_id'), 'leads', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_leads_customer_id'), 'leads', ['customer_id'], unique=False)
    op.create_index(op.f('ix_leads_is_demo'), 'leads', ['is_demo'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.Enum('customer', 'ai', 'human', 'system', name='message_sender'), nullable=False),
    sa.Column('channel_message_id', sa.String(length=128), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'channel_message_id', name='uq_message_conversation_external')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_leads_is_demo'), table_name='leads')
    op.drop_index(op.f('ix_leads_customer_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_conversation_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_business_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_handoff_tasks_conversation_id'), table_name='handoff_tasks')
    op.drop_index(op.f('ix_handoff_tasks_business_id'), table_name='handoff_tasks')
    op.drop_table('handoff_tasks')
    op.drop_index(op.f('ix_bookings_resource_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_is_demo'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_conversation_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_business_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_ai_runs_conversation_id'), table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_index(op.f('ix_conversations_is_demo'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_business_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('tool_idempotency')
    op.drop_index(op.f('ix_customers_is_demo'), table_name='customers')
    op.drop_index(op.f('ix_customers_business_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_channels_business_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_businesses_is_demo'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
