"""drop restaurant tables and table_id

Revision ID: c77e47914ea3
Revises: b3e163b5582b
Create Date: 2026-04-30 12:35:37.819377

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c77e47914ea3'
down_revision: str | None = 'b3e163b5582b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Order matters: drop the FK referring to restaurant_tables BEFORE
    # dropping restaurant_tables itself; otherwise Postgres rejects the
    # DROP TABLE because of the dependency.
    op.drop_index(op.f('ix_bookings_table_id'), table_name='bookings')
    op.drop_constraint(op.f('bookings_table_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'table_id')
    op.drop_index(op.f('ix_restaurant_tables_business_id'), table_name='restaurant_tables')
    op.drop_index(op.f('ix_restaurant_tables_is_demo'), table_name='restaurant_tables')
    op.drop_table('restaurant_tables')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('table_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('bookings_table_id_fkey'), 'bookings', 'restaurant_tables', ['table_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_bookings_table_id'), 'bookings', ['table_id'], unique=False)
    op.create_table('restaurant_tables',
    sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_demo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('restaurant_tables_business_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('restaurant_tables_pkey')),
    sa.UniqueConstraint('business_id', 'code', name=op.f('uq_restaurant_table_business_code'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_restaurant_tables_is_demo'), 'restaurant_tables', ['is_demo'], unique=False)
    op.create_index(op.f('ix_restaurant_tables_business_id'), 'restaurant_tables', ['business_id'], unique=False)
    # ### end Alembic commands ###
