"""restaurant tables

Revision ID: b3e163b5582b
Revises: 5f2182a6daaa
Create Date: 2026-04-29 21:03:44.436386

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b3e163b5582b'
down_revision: str | None = '5f2182a6daaa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_tables',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'code', name='uq_restaurant_table_business_code')
    )
    op.create_index(op.f('ix_restaurant_tables_business_id'), 'restaurant_tables', ['business_id'], unique=False)
    op.create_index(op.f('ix_restaurant_tables_is_demo'), 'restaurant_tables', ['is_demo'], unique=False)
    op.add_column('bookings', sa.Column('table_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_bookings_table_id'), 'bookings', ['table_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'restaurant_tables', ['table_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_table_id'), table_name='bookings')
    op.drop_column('bookings', 'table_id')
    op.drop_index(op.f('ix_restaurant_tables_is_demo'), table_name='restaurant_tables')
    op.drop_index(op.f('ix_restaurant_tables_business_id'), table_name='restaurant_tables')
    op.drop_table('restaurant_tables')
    # ### end Alembic commands ###
