"""dental catalog + practitioner schedules

Revision ID: 5f2182a6daaa
Revises: b005659e4bbf
Create Date: 2026-04-29 19:18:08.647902

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '5f2182a6daaa'
down_revision: str | None = 'b005659e4bbf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practitioners',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('specialties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioners_business_id'), 'practitioners', ['business_id'], unique=False)
    op.create_index(op.f('ix_practitioners_is_demo'), 'practitioners', ['is_demo'], unique=False)
    op.create_table('services',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('required_specialties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_business_id'), 'services', ['business_id'], unique=False)
    op.create_index(op.f('ix_services_is_demo'), 'services', ['is_demo'], unique=False)
    op.create_table('practitioner_schedules',
    sa.Column('practitioner_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='ck_schedule_day_of_week'),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practitioner_id', 'day_of_week', 'start_time', name='uq_practitioner_dow_start')
    )
    op.create_index(op.f('ix_practitioner_schedules_practitioner_id'), 'practitioner_schedules', ['practitioner_id'], unique=False)
    op.add_column('bookings', sa.Column('practitioner_id', sa.UUID(), nullable=True))
    op.add_column('bookings', sa.Column('service_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_bookings_practitioner_id'), 'bookings', ['practitioner_id'], unique=False)
    op.create_index(op.f('ix_bookings_service_id'), 'bookings', ['service_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'bookings', 'practitioners', ['practitioner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_service_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_practitioner_id'), table_name='bookings')
    op.drop_column('bookings', 'service_id')
    op.drop_column('bookings', 'practitioner_id')
    op.drop_index(op.f('ix_practitioner_schedules_practitioner_id'), table_name='practitioner_schedules')
    op.drop_table('practitioner_schedules')
    op.drop_index(op.f('ix_services_is_demo'), table_name='services')
    op.drop_index(op.f('ix_services_business_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_practitioners_is_demo'), table_name='practitioners')
    op.drop_index(op.f('ix_practitioners_business_id'), table_name='practitioners')
    op.drop_table('practitioners')
    # ### end Alembic commands ###
